// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hotpepper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shop struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameKana         string                 `protobuf:"bytes,3,opt,name=name_kana,json=nameKana,proto3" json:"name_kana,omitempty"`
	Address          string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	StationName      string                 `protobuf:"bytes,5,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	LogoImage        string                 `protobuf:"bytes,6,opt,name=logo_image,json=logoImage,proto3" json:"logo_image,omitempty"`
	Catch            string                 `protobuf:"bytes,7,opt,name=catch,proto3" json:"catch,omitempty"`
	Access           string                 `protobuf:"bytes,8,opt,name=access,proto3" json:"access,omitempty"`
	MobileAccess     string                 `protobuf:"bytes,9,opt,name=mobile_access,json=mobileAccess,proto3" json:"mobile_access,omitempty"`
	Lat              float64                `protobuf:"fixed64,10,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng              float64                `protobuf:"fixed64,11,opt,name=lng,proto3" json:"lng,omitempty"`
	Budget           *Budget                `protobuf:"bytes,12,opt,name=budget,proto3" json:"budget,omitempty"`
	BudgetMemo       string                 `protobuf:"bytes,13,opt,name=budget_memo,json=budgetMemo,proto3" json:"budget_memo,omitempty"`
	Genre            *Genre                 `protobuf:"bytes,14,opt,name=genre,proto3" json:"genre,omitempty"`
	SubGenre         *Genre                 `protobuf:"bytes,15,opt,name=sub_genre,json=subGenre,proto3" json:"sub_genre,omitempty"`
	Capacity         int32                  `protobuf:"varint,16,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Open             string                 `protobuf:"bytes,17,opt,name=open,proto3" json:"open,omitempty"`
	Close            string                 `protobuf:"bytes,18,opt,name=close,proto3" json:"close,omitempty"`
	Photo            *ShopPhoto             `protobuf:"bytes,19,opt,name=photo,proto3" json:"photo,omitempty"`
	Urls             *URLs                  `protobuf:"bytes,20,opt,name=urls,proto3" json:"urls,omitempty"`
	CouponUrls       *CouponURLs            `protobuf:"bytes,21,opt,name=coupon_urls,json=couponUrls,proto3" json:"coupon_urls,omitempty"`
	Course           string                 `protobuf:"bytes,22,opt,name=course,proto3" json:"course,omitempty"`
	FreeDrink        string                 `protobuf:"bytes,23,opt,name=free_drink,json=freeDrink,proto3" json:"free_drink,omitempty"`
	FreeFood         string                 `protobuf:"bytes,24,opt,name=free_food,json=freeFood,proto3" json:"free_food,omitempty"`
	PrivateRoom      string                 `protobuf:"bytes,25,opt,name=private_room,json=privateRoom,proto3" json:"private_room,omitempty"`
	Horigotatsu      string                 `protobuf:"bytes,26,opt,name=horigotatsu,proto3" json:"horigotatsu,omitempty"`
	Tatami           string                 `protobuf:"bytes,27,opt,name=tatami,proto3" json:"tatami,omitempty"`
	Card             string                 `protobuf:"bytes,28,opt,name=card,proto3" json:"card,omitempty"`
	NonSmoking       string                 `protobuf:"bytes,29,opt,name=non_smoking,json=nonSmoking,proto3" json:"non_smoking,omitempty"`
	Charter          string                 `protobuf:"bytes,30,opt,name=charter,proto3" json:"charter,omitempty"`
	Ktai             string                 `protobuf:"bytes,31,opt,name=ktai,proto3" json:"ktai,omitempty"`
	Parking          string                 `protobuf:"bytes,32,opt,name=parking,proto3" json:"parking,omitempty"`
	BarrierFree      string                 `protobuf:"bytes,33,opt,name=barrier_free,json=barrierFree,proto3" json:"barrier_free,omitempty"`
	OtherMemo        string                 `protobuf:"bytes,34,opt,name=other_memo,json=otherMemo,proto3" json:"other_memo,omitempty"`
	Sommelier        string                 `protobuf:"bytes,35,opt,name=sommelier,proto3" json:"sommelier,omitempty"`
	OpenAir          string                 `protobuf:"bytes,36,opt,name=open_air,json=openAir,proto3" json:"open_air,omitempty"`
	Show             string                 `protobuf:"bytes,37,opt,name=show,proto3" json:"show,omitempty"`
	Equipment        string                 `protobuf:"bytes,38,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Karaoke          string                 `protobuf:"bytes,39,opt,name=karaoke,proto3" json:"karaoke,omitempty"`
	Band             string                 `protobuf:"bytes,40,opt,name=band,proto3" json:"band,omitempty"`
	Tv               string                 `protobuf:"bytes,41,opt,name=tv,proto3" json:"tv,omitempty"`
	English          string                 `protobuf:"bytes,42,opt,name=english,proto3" json:"english,omitempty"`
	Pet              string                 `protobuf:"bytes,43,opt,name=pet,proto3" json:"pet,omitempty"`
	Child            string                 `protobuf:"bytes,44,opt,name=child,proto3" json:"child,omitempty"`
	Lunch            string                 `protobuf:"bytes,45,opt,name=lunch,proto3" json:"lunch,omitempty"`
	Midnight         string                 `protobuf:"bytes,46,opt,name=midnight,proto3" json:"midnight,omitempty"`
	ShopDetailMemo   string                 `protobuf:"bytes,47,opt,name=shop_detail_memo,json=shopDetailMemo,proto3" json:"shop_detail_memo,omitempty"`
	LargeServiceArea *Area                  `protobuf:"bytes,48,opt,name=large_service_area,json=largeServiceArea,proto3" json:"large_service_area,omitempty"`
	ServiceArea      *Area                  `protobuf:"bytes,49,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	LargeArea        *Area                  `protobuf:"bytes,50,opt,name=large_area,json=largeArea,proto3" json:"large_area,omitempty"`
	MiddleArea       *Area                  `protobuf:"bytes,51,opt,name=middle_area,json=middleArea,proto3" json:"middle_area,omitempty"`
	SmallArea        *Area                  `protobuf:"bytes,52,opt,name=small_area,json=smallArea,proto3" json:"small_area,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_proto_hotpepper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{0}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetNameKana() string {
	if x != nil {
		return x.NameKana
	}
	return ""
}

func (x *Shop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Shop) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *Shop) GetLogoImage() string {
	if x != nil {
		return x.LogoImage
	}
	return ""
}

func (x *Shop) GetCatch() string {
	if x != nil {
		return x.Catch
	}
	return ""
}

func (x *Shop) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Shop) GetMobileAccess() string {
	if x != nil {
		return x.MobileAccess
	}
	return ""
}

func (x *Shop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Shop) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Shop) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *Shop) GetBudgetMemo() string {
	if x != nil {
		return x.BudgetMemo
	}
	return ""
}

func (x *Shop) GetGenre() *Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *Shop) GetSubGenre() *Genre {
	if x != nil {
		return x.SubGenre
	}
	return nil
}

func (x *Shop) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Shop) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Shop) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Shop) GetPhoto() *ShopPhoto {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *Shop) GetUrls() *URLs {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Shop) GetCouponUrls() *CouponURLs {
	if x != nil {
		return x.CouponUrls
	}
	return nil
}

func (x *Shop) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *Shop) GetFreeDrink() string {
	if x != nil {
		return x.FreeDrink
	}
	return ""
}

func (x *Shop) GetFreeFood() string {
	if x != nil {
		return x.FreeFood
	}
	return ""
}

func (x *Shop) GetPrivateRoom() string {
	if x != nil {
		return x.PrivateRoom
	}
	return ""
}

func (x *Shop) GetHorigotatsu() string {
	if x != nil {
		return x.Horigotatsu
	}
	return ""
}

func (x *Shop) GetTatami() string {
	if x != nil {
		return x.Tatami
	}
	return ""
}

func (x *Shop) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *Shop) GetNonSmoking() string {
	if x != nil {
		return x.NonSmoking
	}
	return ""
}

func (x *Shop) GetCharter() string {
	if x != nil {
		return x.Charter
	}
	return ""
}

func (x *Shop) GetKtai() string {
	if x != nil {
		return x.Ktai
	}
	return ""
}

func (x *Shop) GetParking() string {
	if x != nil {
		return x.Parking
	}
	return ""
}

func (x *Shop) GetBarrierFree() string {
	if x != nil {
		return x.BarrierFree
	}
	return ""
}

func (x *Shop) GetOtherMemo() string {
	if x != nil {
		return x.OtherMemo
	}
	return ""
}

func (x *Shop) GetSommelier() string {
	if x != nil {
		return x.Sommelier
	}
	return ""
}

func (x *Shop) GetOpenAir() string {
	if x != nil {
		return x.OpenAir
	}
	return ""
}

func (x *Shop) GetShow() string {
	if x != nil {
		return x.Show
	}
	return ""
}

func (x *Shop) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *Shop) GetKaraoke() string {
	if x != nil {
		return x.Karaoke
	}
	return ""
}

func (x *Shop) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

func (x *Shop) GetTv() string {
	if x != nil {
		return x.Tv
	}
	return ""
}

func (x *Shop) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Shop) GetPet() string {
	if x != nil {
		return x.Pet
	}
	return ""
}

func (x *Shop) GetChild() string {
	if x != nil {
		return x.Child
	}
	return ""
}

func (x *Shop) GetLunch() string {
	if x != nil {
		return x.Lunch
	}
	return ""
}

func (x *Shop) GetMidnight() string {
	if x != nil {
		return x.Midnight
	}
	return ""
}

func (x *Shop) GetShopDetailMemo() string {
	if x != nil {
		return x.ShopDetailMemo
	}
	return ""
}

func (x *Shop) GetLargeServiceArea() *Area {
	if x != nil {
		return x.LargeServiceArea
	}
	return nil
}

func (x *Shop) GetServiceArea() *Area {
	if x != nil {
		return x.ServiceArea
	}
	return nil
}

func (x *Shop) GetLargeArea() *Area {
	if x != nil {
		return x.LargeArea
	}
	return nil
}

func (x *Shop) GetMiddleArea() *Area {
	if x != nil {
		return x.MiddleArea
	}
	return nil
}

func (x *Shop) GetSmallArea() *Area {
	if x != nil {
		return x.SmallArea
	}
	return nil
}

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_proto_hotpepper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{1}
}

func (x *Area) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Catch         string                 `protobuf:"bytes,3,opt,name=catch,proto3" json:"catch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_hotpepper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{2}
}

func (x *Genre) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetCatch() string {
	if x != nil {
		return x.Catch
	}
	return ""
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Average       string                 `protobuf:"bytes,3,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_proto_hotpepper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{3}
}

func (x *Budget) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Budget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Budget) GetAverage() string {
	if x != nil {
		return x.Average
	}
	return ""
}

type URLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pc            string                 `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLs) Reset() {
	*x = URLs{}
	mi := &file_proto_hotpepper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLs) ProtoMessage() {}

func (x *URLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLs.ProtoReflect.Descriptor instead.
func (*URLs) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{4}
}

func (x *URLs) GetPc() string {
	if x != nil {
		return x.Pc
	}
	return ""
}

type CouponURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pc            string                 `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
	Sp            string                 `protobuf:"bytes,2,opt,name=sp,proto3" json:"sp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponURLs) Reset() {
	*x = CouponURLs{}
	mi := &file_proto_hotpepper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponURLs) ProtoMessage() {}

func (x *CouponURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponURLs.ProtoReflect.Descriptor instead.
func (*CouponURLs) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{5}
}

func (x *CouponURLs) GetPc() string {
	if x != nil {
		return x.Pc
	}
	return ""
}

func (x *CouponURLs) GetSp() string {
	if x != nil {
		return x.Sp
	}
	return ""
}

type ShopPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pc            *ShopPhotoPC           `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
	Mobile        *ShopPhotoMobile       `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopPhoto) Reset() {
	*x = ShopPhoto{}
	mi := &file_proto_hotpepper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopPhoto) ProtoMessage() {}

func (x *ShopPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopPhoto.ProtoReflect.Descriptor instead.
func (*ShopPhoto) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{6}
}

func (x *ShopPhoto) GetPc() *ShopPhotoPC {
	if x != nil {
		return x.Pc
	}
	return nil
}

func (x *ShopPhoto) GetMobile() *ShopPhotoMobile {
	if x != nil {
		return x.Mobile
	}
	return nil
}

type ShopPhotoPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L             string                 `protobuf:"bytes,1,opt,name=l,proto3" json:"l,omitempty"`
	M             string                 `protobuf:"bytes,2,opt,name=m,proto3" json:"m,omitempty"`
	S             string                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopPhotoPC) Reset() {
	*x = ShopPhotoPC{}
	mi := &file_proto_hotpepper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopPhotoPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopPhotoPC) ProtoMessage() {}

func (x *ShopPhotoPC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopPhotoPC.ProtoReflect.Descriptor instead.
func (*ShopPhotoPC) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{7}
}

func (x *ShopPhotoPC) GetL() string {
	if x != nil {
		return x.L
	}
	return ""
}

func (x *ShopPhotoPC) GetM() string {
	if x != nil {
		return x.M
	}
	return ""
}

func (x *ShopPhotoPC) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type ShopPhotoMobile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L             string                 `protobuf:"bytes,1,opt,name=l,proto3" json:"l,omitempty"`
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopPhotoMobile) Reset() {
	*x = ShopPhotoMobile{}
	mi := &file_proto_hotpepper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopPhotoMobile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopPhotoMobile) ProtoMessage() {}

func (x *ShopPhotoMobile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotpepper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopPhotoMobile.ProtoReflect.Descriptor instead.
func (*ShopPhotoMobile) Descriptor() ([]byte, []int) {
	return file_proto_hotpepper_proto_rawDescGZIP(), []int{8}
}

func (x *ShopPhotoMobile) GetL() string {
	if x != nil {
		return x.L
	}
	return ""
}

func (x *ShopPhotoMobile) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_proto_hotpepper_proto protoreflect.FileDescriptor

const file_proto_hotpepper_proto_rawDesc = "" +
	"\n" +
	"\x15proto/hotpepper.proto\x12\x05proto\"\x9c\f\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tname_kana\x18\x03 \x01(\tR\bnameKana\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\fstation_name\x18\x05 \x01(\tR\vstationName\x12\x1d\n" +
	"\n" +
	"logo_image\x18\x06 \x01(\tR\tlogoImage\x12\x14\n" +
	"\x05catch\x18\a \x01(\tR\x05catch\x12\x16\n" +
	"\x06access\x18\b \x01(\tR\x06access\x12#\n" +
	"\rmobile_access\x18\t \x01(\tR\fmobileAccess\x12\x10\n" +
	"\x03lat\x18\n" +
	" \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\v \x01(\x01R\x03lng\x12%\n" +
	"\x06budget\x18\f \x01(\v2\r.proto.BudgetR\x06budget\x12\x1f\n" +
	"\vbudget_memo\x18\r \x01(\tR\n" +
	"budgetMemo\x12\"\n" +
	"\x05genre\x18\x0e \x01(\v2\f.proto.GenreR\x05genre\x12)\n" +
	"\tsub_genre\x18\x0f \x01(\v2\f.proto.GenreR\bsubGenre\x12\x1a\n" +
	"\bcapacity\x18\x10 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04open\x18\x11 \x01(\tR\x04open\x12\x14\n" +
	"\x05close\x18\x12 \x01(\tR\x05close\x12&\n" +
	"\x05photo\x18\x13 \x01(\v2\x10.proto.ShopPhotoR\x05photo\x12\x1f\n" +
	"\x04urls\x18\x14 \x01(\v2\v.proto.URLsR\x04urls\x122\n" +
	"\vcoupon_urls\x18\x15 \x01(\v2\x11.proto.CouponURLsR\n" +
	"couponUrls\x12\x16\n" +
	"\x06course\x18\x16 \x01(\tR\x06course\x12\x1d\n" +
	"\n" +
	"free_drink\x18\x17 \x01(\tR\tfreeDrink\x12\x1b\n" +
	"\tfree_food\x18\x18 \x01(\tR\bfreeFood\x12!\n" +
	"\fprivate_room\x18\x19 \x01(\tR\vprivateRoom\x12 \n" +
	"\vhorigotatsu\x18\x1a \x01(\tR\vhorigotatsu\x12\x16\n" +
	"\x06tatami\x18\x1b \x01(\tR\x06tatami\x12\x12\n" +
	"\x04card\x18\x1c \x01(\tR\x04card\x12\x1f\n" +
	"\vnon_smoking\x18\x1d \x01(\tR\n" +
	"nonSmoking\x12\x18\n" +
	"\acharter\x18\x1e \x01(\tR\acharter\x12\x12\n" +
	"\x04ktai\x18\x1f \x01(\tR\x04ktai\x12\x18\n" +
	"\aparking\x18  \x01(\tR\aparking\x12!\n" +
	"\fbarrier_free\x18! \x01(\tR\vbarrierFree\x12\x1d\n" +
	"\n" +
	"other_memo\x18\" \x01(\tR\totherMemo\x12\x1c\n" +
	"\tsommelier\x18# \x01(\tR\tsommelier\x12\x19\n" +
	"\bopen_air\x18$ \x01(\tR\aopenAir\x12\x12\n" +
	"\x04show\x18% \x01(\tR\x04show\x12\x1c\n" +
	"\tequipment\x18& \x01(\tR\tequipment\x12\x18\n" +
	"\akaraoke\x18' \x01(\tR\akaraoke\x12\x12\n" +
	"\x04band\x18( \x01(\tR\x04band\x12\x0e\n" +
	"\x02tv\x18) \x01(\tR\x02tv\x12\x18\n" +
	"\aenglish\x18* \x01(\tR\aenglish\x12\x10\n" +
	"\x03pet\x18+ \x01(\tR\x03pet\x12\x14\n" +
	"\x05child\x18, \x01(\tR\x05child\x12\x14\n" +
	"\x05lunch\x18- \x01(\tR\x05lunch\x12\x1a\n" +
	"\bmidnight\x18. \x01(\tR\bmidnight\x12(\n" +
	"\x10shop_detail_memo\x18/ \x01(\tR\x0eshopDetailMemo\x129\n" +
	"\x12large_service_area\x180 \x01(\v2\v.proto.AreaR\x10largeServiceArea\x12.\n" +
	"\fservice_area\x181 \x01(\v2\v.proto.AreaR\vserviceArea\x12*\n" +
	"\n" +
	"large_area\x182 \x01(\v2\v.proto.AreaR\tlargeArea\x12,\n" +
	"\vmiddle_area\x183 \x01(\v2\v.proto.AreaR\n" +
	"middleArea\x12*\n" +
	"\n" +
	"small_area\x184 \x01(\v2\v.proto.AreaR\tsmallArea\".\n" +
	"\x04Area\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"E\n" +
	"\x05Genre\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05catch\x18\x03 \x01(\tR\x05catch\"J\n" +
	"\x06Budget\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaverage\x18\x03 \x01(\tR\aaverage\"\x16\n" +
	"\x04URLs\x12\x0e\n" +
	"\x02pc\x18\x01 \x01(\tR\x02pc\",\n" +
	"\n" +
	"CouponURLs\x12\x0e\n" +
	"\x02pc\x18\x01 \x01(\tR\x02pc\x12\x0e\n" +
	"\x02sp\x18\x02 \x01(\tR\x02sp\"_\n" +
	"\tShopPhoto\x12\"\n" +
	"\x02pc\x18\x01 \x01(\v2\x12.proto.ShopPhotoPCR\x02pc\x12.\n" +
	"\x06mobile\x18\x02 \x01(\v2\x16.proto.ShopPhotoMobileR\x06mobile\"7\n" +
	"\vShopPhotoPC\x12\f\n" +
	"\x01l\x18\x01 \x01(\tR\x01l\x12\f\n" +
	"\x01m\x18\x02 \x01(\tR\x01m\x12\f\n" +
	"\x01s\x18\x03 \x01(\tR\x01s\"-\n" +
	"\x0fShopPhotoMobile\x12\f\n" +
	"\x01l\x18\x01 \x01(\tR\x01l\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01sB\tZ\a./protob\x06proto3"

var (
	file_proto_hotpepper_proto_rawDescOnce sync.Once
	file_proto_hotpepper_proto_rawDescData []byte
)

func file_proto_hotpepper_proto_rawDescGZIP() []byte {
	file_proto_hotpepper_proto_rawDescOnce.Do(func() {
		file_proto_hotpepper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hotpepper_proto_rawDesc), len(file_proto_hotpepper_proto_rawDesc)))
	})
	return file_proto_hotpepper_proto_rawDescData
}

var file_proto_hotpepper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_hotpepper_proto_goTypes = []any{
	(*Shop)(nil),            // 0: proto.Shop
	(*Area)(nil),            // 1: proto.Area
	(*Genre)(nil),           // 2: proto.Genre
	(*Budget)(nil),          // 3: proto.Budget
	(*URLs)(nil),            // 4: proto.URLs
	(*CouponURLs)(nil),      // 5: proto.CouponURLs
	(*ShopPhoto)(nil),       // 6: proto.ShopPhoto
	(*ShopPhotoPC)(nil),     // 7: proto.ShopPhotoPC
	(*ShopPhotoMobile)(nil), // 8: proto.ShopPhotoMobile
}
var file_proto_hotpepper_proto_depIdxs = []int32{
	3,  // 0: proto.Shop.budget:type_name -> proto.Budget
	2,  // 1: proto.Shop.genre:type_name -> proto.Genre
	2,  // 2: proto.Shop.sub_genre:type_name -> proto.Genre
	6,  // 3: proto.Shop.photo:type_name -> proto.ShopPhoto
	4,  // 4: proto.Shop.urls:type_name -> proto.URLs
	5,  // 5: proto.Shop.coupon_urls:type_name -> proto.CouponURLs
	1,  // 6: proto.Shop.large_service_area:type_name -> proto.Area
	1,  // 7: proto.Shop.service_area:type_name -> proto.Area
	1,  // 8: proto.Shop.large_area:type_name -> proto.Area
	1,  // 9: proto.Shop.middle_area:type_name -> proto.Area
	1,  // 10: proto.Shop.small_area:type_name -> proto.Area
	7,  // 11: proto.ShopPhoto.pc:type_name -> proto.ShopPhotoPC
	8,  // 12: proto.ShopPhoto.mobile:type_name -> proto.ShopPhotoMobile
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_hotpepper_proto_init() }
func file_proto_hotpepper_proto_init() {
	if File_proto_hotpepper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotpepper_proto_rawDesc), len(file_proto_hotpepper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hotpepper_proto_goTypes,
		DependencyIndexes: file_proto_hotpepper_proto_depIdxs,
		MessageInfos:      file_proto_hotpepper_proto_msgTypes,
	}.Build()
	File_proto_hotpepper_proto = out.File
	file_proto_hotpepper_proto_goTypes = nil
	file_proto_hotpepper_proto_depIdxs = nil
}
