// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mcp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchHotpepperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           string                 `protobuf:"bytes,3,opt,name=lng,proto3" json:"lng,omitempty"`
	RangeStr      string                 `protobuf:"bytes,4,opt,name=rangeStr,proto3" json:"rangeStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotpepperRequest) Reset() {
	*x = SearchHotpepperRequest{}
	mi := &file_proto_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotpepperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotpepperRequest) ProtoMessage() {}

func (x *SearchHotpepperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotpepperRequest.ProtoReflect.Descriptor instead.
func (*SearchHotpepperRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHotpepperRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchHotpepperRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *SearchHotpepperRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *SearchHotpepperRequest) GetRangeStr() string {
	if x != nil {
		return x.RangeStr
	}
	return ""
}

type SearchHotpepperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       *Results               `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotpepperResponse) Reset() {
	*x = SearchHotpepperResponse{}
	mi := &file_proto_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotpepperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotpepperResponse) ProtoMessage() {}

func (x *SearchHotpepperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotpepperResponse.ProtoReflect.Descriptor instead.
func (*SearchHotpepperResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHotpepperResponse) GetResults() *Results {
	if x != nil {
		return x.Results
	}
	return nil
}

type Results struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Api              string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ResultsAvailable int32                  `protobuf:"varint,2,opt,name=results_available,json=resultsAvailable,proto3" json:"results_available,omitempty"`
	ResultsReturned  string                 `protobuf:"bytes,3,opt,name=results_returned,json=resultsReturned,proto3" json:"results_returned,omitempty"`
	ResultsStart     int32                  `protobuf:"varint,4,opt,name=results_start,json=resultsStart,proto3" json:"results_start,omitempty"`
	Shops            []*Shop                `protobuf:"bytes,5,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Results) Reset() {
	*x = Results{}
	mi := &file_proto_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *Results) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *Results) GetResultsAvailable() int32 {
	if x != nil {
		return x.ResultsAvailable
	}
	return 0
}

func (x *Results) GetResultsReturned() string {
	if x != nil {
		return x.ResultsReturned
	}
	return ""
}

func (x *Results) GetResultsStart() int32 {
	if x != nil {
		return x.ResultsStart
	}
	return 0
}

func (x *Results) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

var File_proto_mcp_proto protoreflect.FileDescriptor

const file_proto_mcp_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mcp.proto\x12\x05proto\x1a\x15proto/hotpepper.proto\"r\n" +
	"\x16SearchHotpepperRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\tR\x03lng\x12\x1a\n" +
	"\brangeStr\x18\x04 \x01(\tR\brangeStr\"C\n" +
	"\x17SearchHotpepperResponse\x12(\n" +
	"\aresults\x18\x01 \x01(\v2\x0e.proto.ResultsR\aresults\"\xbb\x01\n" +
	"\aResults\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03api\x12+\n" +
	"\x11results_available\x18\x02 \x01(\x05R\x10resultsAvailable\x12)\n" +
	"\x10results_returned\x18\x03 \x01(\tR\x0fresultsReturned\x12#\n" +
	"\rresults_start\x18\x04 \x01(\x05R\fresultsStart\x12!\n" +
	"\x05shops\x18\x05 \x03(\v2\v.proto.ShopR\x05shopsB\tZ\a./protob\x06proto3"

var (
	file_proto_mcp_proto_rawDescOnce sync.Once
	file_proto_mcp_proto_rawDescData []byte
)

func file_proto_mcp_proto_rawDescGZIP() []byte {
	file_proto_mcp_proto_rawDescOnce.Do(func() {
		file_proto_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)))
	})
	return file_proto_mcp_proto_rawDescData
}

var file_proto_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_mcp_proto_goTypes = []any{
	(*SearchHotpepperRequest)(nil),  // 0: proto.SearchHotpepperRequest
	(*SearchHotpepperResponse)(nil), // 1: proto.SearchHotpepperResponse
	(*Results)(nil),                 // 2: proto.Results
	(*Shop)(nil),                    // 3: proto.Shop
}
var file_proto_mcp_proto_depIdxs = []int32{
	2, // 0: proto.SearchHotpepperResponse.results:type_name -> proto.Results
	3, // 1: proto.Results.shops:type_name -> proto.Shop
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mcp_proto_init() }
func file_proto_mcp_proto_init() {
	if File_proto_mcp_proto != nil {
		return
	}
	file_proto_hotpepper_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mcp_proto_goTypes,
		DependencyIndexes: file_proto_mcp_proto_depIdxs,
		MessageInfos:      file_proto_mcp_proto_msgTypes,
	}.Build()
	File_proto_mcp_proto = out.File
	file_proto_mcp_proto_goTypes = nil
	file_proto_mcp_proto_depIdxs = nil
}
